version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    
    working_directory: /go/src/github.com/devopsdymyr/docker-eb-ci-mon

    steps:
      - checkout

      - setup_remote_docker

      - run:
         name: Install AWS CLI
         command: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - run:
          name: Test
          command: go test
      
      - run:
          name: Build
          command: docker build -t devopsdymyr/avengers:latest .
      
      - run:
          name: Push
          command: |
            docker login -u$DOCKERHUB_LOGIN -p$DOCKERHUB_PASSWORD
            docker tag devopsdymyr/avengers:latest devopsdymyr/avengers:${CIRCLE_SHA1}
            docker push devopsdymyr/avengers:latest
            docker push devopsdymyr/avengers:${CIRCLE_SHA1}
      
      - run:
          name: Deploy
          command: |
            zip -r deployment-${CIRCLE_SHA1}.zip .
            aws s3 cp deployment-${CIRCLE_SHA1}.zip s3://avengers-docker-eb1 --region eu-west-3
            aws elasticbeanstalk create-application-version --application-name avengers \
                --version-label ${CIRCLE_SHA1} --source-bundle S3Bucket="avengers-docker-eb1",S3Key="deployment-${CIRCLE_SHA1}.zip" --region eu-west-3
            aws elasticbeanstalk update-environment --application-name avengers \
                --environment-name staging --version-label ${CIRCLE_SHA1} --region eu-west-3
